app_name = "mf-qi"
app_env = "development"

[database]
url = "postgres://postgres:postgres@localhost:5432/cuba"
max_connections = 20

[redis]
url = "redis://localhost:6379"

[server]
host = "127.0.0.1"
port = 50092

[telemetry]
log_level = "debug"
