app_name = "hr-ex"
app_env = "development"

[database]
url = "postgres://postgres:postgres@localhost:5432/erp"
max_connections = 20

[redis]
url = "redis://localhost:6379"

[server]
host = "127.0.0.1"
port = 50111

[telemetry]
log_level = "debug"
